<?php
/**
 * Created by PhpStorm.
 * User: if-information
 * Date: 2017/11/7
 * Time: 下午3:10
 */
namespace app\api\controller;
use app\common\lib\Aes;
use app\common\lib\ApiException;

class AuthBase extends Base
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $res = $this->isLogin();
        if (!$res)
        {
            throw new ApiException('用户未登录',403);
        }
    }

    /**
     * 验证用户是否登录
     * @return bool
     *
     */
    public function isLogin()
    {
        //获取前端发送过来的token
        $header = request()->header();
        $access_token = $header['access_user_token'];
        //对access_token进行基本的验证
        if (!$access_token['access_user_token'])
        {
            return false;
        }

        //对access_token进行解密 获取到真正的token值
        $access_token = (new Aes())->decrypt($access_token);
        if (!strpos($access_token,'||'))
        {
            return false;
        }

        //根据token值从数据库获取用户信息
        list($token ,$id) = explode($access_token,'||');
        $user = model('User')->get(['token' => $token]);

        //使用当前时间和time_out时间做对比  如果大于 说明 过期  需要重新登录 返回false
        if (time() > $user['time_out'])
        {
            return false;
        }
        $this->user = $user;
        return true;
    }
}
